### ISSUE TITLE
Let's call it...

### ISSUE THREAD

**Issue by marcelinhov2** [DomPhysis/bolt#2]
Galera, precisamos da ajuda de vocês para criar um nome para o stack de front que foi apresentado quinta-feira ( 21/04/16 ) na Domphysis.

Após decidirmos o nome, ficou um débito técnico com o @matheuspoleza para renomear tudo dentro do stack ( https://github.com/DomPhysis/microservices-bootstraper/pull/1 )

Let's the game begins...

**Comment by tmatias** [comment]
frontend-microservice-template

**Comment by cirocfc** [comment]
frontend-microservice-bootstrapper ??
frontend-bootstrapper ??

**Comment by marcelinhov2** [comment]
[v8](https://pt.wikipedia.org/wiki/Motor_V8) - "...e são utilizados em automóveis de grande porte, utilitários leves, médios e pesados, embarcações marítimas e até mesmo aeronáuticas."

Multiuso e potente s2

**Comment by fernahh** [comment]
V8 já é conhecido no ~front-end~ por ser a engine do Chrome https://developers.google.com/v8/

**Comment by marcelinhov2** [comment]
Maldito Google... mal posso ver seus movimentos... :(

**Comment by fernahh** [comment]
**calve**

![screenshot from 2016-04-27 14-55-59](https://cloud.githubusercontent.com/assets/2369851/14862519/33364430-0c88-11e6-8d7a-959f16e7ce8a.png)

ou **midwife**

![screenshot from 2016-04-27 14-56-53](https://cloud.githubusercontent.com/assets/2369851/14862545/4d29a062-0c88-11e6-9795-4b49fbff08f7.png)

**Comment by fernahh** [comment]
**Bolt**

![Bolt](http://midias.folhavitoria.com.br/files/2015/02/34292502-brand-bio-bsfc-157955-sf-2997-005-20140327-v1-hd-768x432-16x9.jpg)

**Comment by matheuspoleza** [comment]
bolt, why not? haha ++
